name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Testing Phase
        run: |
          mvn clean
          mvn verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
